correcionEsquemaUsuario
Sarapr27/ReStore pull request #9
Opened 2023-06-13 21:03 UTC by LucaVera13

Agregue el codigo postal y meti la carpeta de models a database

2023-06-13 21:05 UTC, LucaFrisoni approved these changes

2023-06-13 21:06 UTC, LucaFrisoni commented
Necesitas 2 approbes, hablale a sara para que lo modifique a 1 o mandale a otro mas

2023-06-13 21:10 UTC, LucaFrisoni requested changes
Esta mal el requiere. solo tenes que traer mongoose = requiere("mongoose")

2023-06-13 21:15 UTC, LucaVera13 commented
> Esta mal el requiere. solo tenes que traer mongoose = requiere("mongoose")

por lo poco que vi de mongo y mongoose no hay ningun error, requeri el schema para hacer uno y el model para crearlo, estas seguro que esta mal ?

2023-06-13 21:15 UTC, psamirt approved these changes

2023-06-13 21:17 UTC, psamirt approved these changes

2023-06-13 22:38 UTC, LucaFrisoni commented
> 

creeria, segun chatGPT

2023-06-14 00:55 UTC, jerenob1999 approved these changes

2023-06-14 01:05 UTC, LucaFrisoni approved these changes

2023-06-14 03:30 UTC, merged